Fix compilation error for 64-bit little endian build: libexec/rtld-elf/mips/reloc.c:196: warning: right shift count >= width of type
When the expression '(r_info) >> 32' was passed to bswap32() it was promptly
changed to '(uint32_t)(r_info) >> 32' which is not what we intended.


git-svn-id: svn+ssh://svn.freebsd.org/base/head@211130 ccf9f872-aa2e-dd11-9fc8-001c23d0bc1f